export * from "./BatyshkaSection";
export * from "./CardSection";
export * from "./SliderSection";
export * from "./QRSection";
export * from "./TopSection";
export * from "./MapSection";
export * from "./ReadySection";
export * from "./SuitsSection";
export * from "./OfferSection";
